### ISSUE TITLE
Wasm Light Client Module - client state methods and unit testing

### ISSUE THREAD

**Issue by misko9** [strangelove-ventures/ibc-go#8]
## Requirements document

TBD

### Client

| Interchain Standard Number                                      | Standard Title             | Stage | Implementations |
| --------------------------------------------------------------- | -------------------------- | ----- | --------------- |
| [8](https://github.com/cosmos/ibc/blob/main/spec/client/ics-008-wasm-client/README.md)                  | Wasm Client                | Draft | |
| [10](https://github.com/cosmos/ibc/blob/main/spec/client/ics-010-grandpa-client/README.md)              | GRANDPA Client             | Draft | |

## ADRs

| ADR \# | Description | Status |
| ------ | ----------- | ------ |
| [027](https://github.com/cosmos/ibc-go/blob/main/docs/architecture/adr-027-ibc-wasm.md) | Wasm based light clients | Accepted |

## Milestones

- [ ] Implement client state methods related to handling misbehaviours
- [ ] Complete implementation of generic function for updating client state
- [ ] Complete VerifyUpgradeAndUpdateState method
- [ ] Wasm tests for checking functionalities of client state methods

## Implementation issues

TBD

## QA scenarios

TBD

## Automated e2e tests

TBD

## Pre-releases

TBD

## Checklist

- [ ] Internal audit(s)
- [ ] External audit(s)
- [ ] Documentation
- [ ] Swagger
- [ ] Integration with relayers:
  - [ ] Hermes
  - [ ] Rly

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by misko9** [comment]
Tracking in #3
